version: "3.9"
services:
  user-service:
    build: ./user-service
    ports:
      - "3000:3000"
    env_file: ./.env

  course-service:
    build: ./course-service
    ports:
      - "3001:3001"
    env_file: ./.env

  frontend:
    build: ./frontend
    ports:
      - "3002:80"
