name: CD Pipeline

on:
  push:
    paths:
      - "app/terraform/**"

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      ARM_USE_OIDC: true
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_USE_AZUREAD: true

      TF_VAR_acr_name: ${{ secrets.AZURE_ACR_NAME }}
      TF_VAR_rg_name: ${{ secrets.AZURE_RG_NAME }}
      TF_VAR_location: "East US"
      TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}

      TF_VAR_app_name: "smart-learn-app"
      TF_VAR_db_host: "smartlearningdb.postgres.database.azure.com"
      TF_VAR_email: "127156089@sastra.ac.in.com"

    steps:
      - uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          allow-no-subscriptions: true

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Terraform Init
        run: terraform -chdir=app/terraform init -reconfigure

      - name: Terraform Validate
        run: terraform -chdir=app/terraform validate

      - name: Terraform Plan
        run: terraform -chdir=app/terraform plan -out=tfplan -input=false -no-color

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform -chdir=app/terraform apply -auto-approve tfplan
